##############################################################################
# Copyright (c) 2014-20, Lawrence Livermore National Security, LLC and Conduit
# project contributors. See the COPYRIGHT file for details.
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONDUIT_ALLOC_NAME: conduit_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_BUILDS_DIR}/conduit_${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  INSTALL_ROOT: ${CI_BUILDS_DIR}/spack_uberenv
  SPACK_UPSTREAM: /usr/workspace/radiuss/spack-chain-parent/opt/spack

stages:
  - allocate_resources
  - deps
  - install
  - release_resources
  - clean

# Some scripts
.run_update_uberenv: &run_update_uberenv |
  [[ -n "${UPDATE_UBERENV}" ]] && ./scripts/ci/update-uberenv.sh "${UPDATE_UBERENV}"

.def_uberenv_cmd: &def_uberenv_cmd |
  INSTALL=""
  [[ "${UBERENV_INSTALL}" == "ON" ]] && INSTALL="--install --run_tests"
  PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
  UPSTREAM="--upstream=${SPACK_UPSTREAM}"
  SPEC="--spec=${PKG_SPEC}"
  UBERENV_CMD="scripts/uberenv/uberenv.py ${INSTALL} ${SPEC} ${PREFIX} ${UPSTREAM}"

# Build modes
.mode_deps:
  stage: deps
  variables:
    UBERENV_INSTALL: "OFF"

.mode_install:
  stage: install
  variables:
    UBERENV_INSTALL: "ON"

##################
# QUARTZ TEMPLATES
##################

# Shared configuration of jobs for quartz
.on_quartz:
  tags:
    - shell
    - quartz
  timeout: 3h
  except:
    refs:
      - /_qnone/
    variables:
      - $CONDUIT_CI_QUARTZ == "OFF"

# Allocation sequence
.def_srun_prefix: &def_srun_prefix |
  JOB_ID=$(squeue -h --name=${CONDUIT_ALLOC_NAME} --format=%A)
  [[ -n "${JOB_ID}" ]] && JOB_ID="--jobid=${JOB_ID}"
  RESOURCES="-N 1 -n 1 -c 12"
  export SRUN_PREFIX="srun ${JOB_ID} ${RESOURCES}"

# Template defining the generic script for quartz
.srun_build_script:
  script:
    - *run_update_uberenv
    - *def_srun_prefix
    - *def_uberenv_cmd
    - set -x; ${SRUN_PREFIX} ${UBERENV_CMD}; set +x

####
# Generic qwartz jobs
.build_deps_on_quartz:
  extends: [.srun_build_script, .mode_deps, .on_quartz]

.install_on_quartz:
  extends: [.srun_build_script, .mode_install, .on_quartz]

##################
# LASSEN TEMPLATES
##################

# Shared configuration of jobs for lassen
.on_lassen:
  variables:
  tags:
    - shell
    - lassen
  rules:
    - if: '$CI_COMMIT_BRANCH =~/_lnone/ || $CONDUIT_CI_LASSEN == "OFF"'
      when: never
    - when: on_success
  allow_failure: true

# Template defining the generic script for lassen
.lsf_build_script:
  script:
    - *run_update_uberenv
    - *def_uberenv_cmd
    - set -x; lalloc 1 ${UBERENV_CMD}; set +x

####
# Generic lassen jobs
.build_deps_on_lassen:
  extends: [.lsf_build_script, .mode_deps, .on_lassen]

.install_on_lassen:
  extends: [.lsf_build_script, .mode_install, .on_lassen]

############
# TOOLCHAINS
############

.with_gcc:
  variables:
    TOOLCHAIN: "gcc"
    PKG_SPEC: ""

.with_gcc_static:
  variables:
    TOOLCHAIN: "gcc_static"
    PKG_SPEC: "%gcc~shared"

.with_clang:
  variables:
    TOOLCHAIN: "clang"
    PKG_SPEC: "%clang@coral~python~fortran"

.with_xl:
  variables:
    TOOLCHAIN: "xl"
    PKG_SPEC: "%xl@coral~shared~python~fortran"

################
# JOBS INCLUSION
################

# This is where jobs are included
include:
  - local: .gitlab/ci/build_quartz.yml
  - local: .gitlab/ci/build_lassen.yml
