##############################################################################
# Copyright (c) 2014-20, Lawrence Livermore National Security, LLC and Conduit
# project contributors. See the COPYRIGHT file for details.
##############################################################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  INSTALL_ROOT: ${CI_BUILDS_DIR}/conduit/${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}/uberenv_libs
  SPACK_UPSTREAM: /usr/workspace/radiuss/spack-chain-parent/opt/spack

stages:
  - deps
  - install

#########
# SCRIPTS
#########

# Define the generic script
.build_script:
  script:
    # Update uberenv if variable set
    - if [[ -n "${UPDATE_UBERENV}" ]]; then ./scripts/ci/update-uberenv.sh "${UPDATE_UBERENV}"; fi
    # Switch between dependency and install modes
    - INSTALL=""
    - if [[ "${UBERENV_INSTALL}" == "ON" ]]; then INSTALL="--install --run_tests"; fi
    # Preparing command
    - mkdir -p ${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}
    - PREFIX="--prefix=${INSTALL_ROOT}_${SYS_TYPE}_${TOOLCHAIN}"
    - SPEC="--spec=${PKG_SPEC}"
    - UBERENV_CMD="scripts/uberenv/uberenv.py ${INSTALL} ${SPEC} ${PREFIX}"
    # Build command
    - echo "Build command -- ${UBERENV_CMD}"
    - ${UBERENV_CMD}

# Build modes templates:
# A job will have one on this template to pilot the behavior of def_uberenv_cmd
.mode_deps:
  stage: deps
  variables:
    UBERENV_INSTALL: "OFF"

.mode_install:
  stage: install
  variables:
    UBERENV_INSTALL: "ON"

##########
# INCLUDES
##########

# This is where templates and jobs are included
include:
  - local: .gitlab/toolchains_templates.yml
  - local: .gitlab/quartz_templates.yml
  - local: .gitlab/quartz_jobs.yml
  - local: .gitlab/lassen_templates.yml
  - local: .gitlab/lassen_jobs.yml
